train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client1"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./dataset/mnist_dataset.py"
  dataset_name: "get_mnist"
  dataset_kwargs:
    num_clients: 2
    client_id: 0
    partition_strategy: "class_noniid"
    visualization: True
    output_dirname: "./output"
    output_filename: "visualization.pdf"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False
  # proxystore_configs:
  #   enable_proxystore: False
  #   connector_type: "FileConnector"
  #   connector_configs:
  #     store_dir: "./.proxystore_client/cache"
  # proxystore_configs:
  #   enable_proxystore: True
  #   connector_type: "S3Connector"
  #   connector_configs:
  #     s3_bucket: "appfl-bench"
  #     expiration: 3600
  proxystore_configs:
    enable_proxystore: False
    connector_type: "EndpointConnector"
    connector_configs:
      endpoints: ["621982b4-9adb-4aac-a748-18b0b6ec840b", "5c755a5b-3b27-4691-86eb-34a95a492e44"]