client_configs:
  train_configs:
    # Local trainer
    trainer: "NaiveTrainer"
    mode: "step"
    num_local_steps: 0
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn_path: "./loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: False
    do_pre_validation: False
    metric_path: "./metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False
    
  model_configs:
    model_path: "./model/cnn.py"
    model_name: "CNN"
    model_kwargs:
      num_channel: 1
      num_classes: 10
      num_pixel: 28
  
  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

server_configs:
  scheduler: "DummySyncScheduler"
  scheduler_kwargs:
    num_clients: 2
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 30
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
    # proxystore_configs:
    #   enable_proxystore: False
    #   connector_type: "FileConnector"
    #   connector_configs:
    #     store_dir: "./.proxystore_server/cache"
    proxystore_configs:
      enable_proxystore: False
      connector_type: "EndpointConnector"
      connector_configs:
        endpoints: ["621982b4-9adb-4aac-a748-18b0b6ec840b", "5c755a5b-3b27-4691-86eb-34a95a492e44"]
    # proxystore_configs:
    #   enable_proxystore: True
    #   connector_type: "S3Connector"
    #   connector_configs:
    #     s3_bucket: "appfl-bench"
    #     expiration: 3600