client_id: "IOP-Hospital"

train_configs:
  # Local trainer
  trainer: "VanillaTrainer"
  mode: "step"
  num_local_steps: 50
  optim: "AdamW"
  optim_args:
    lr: 0.001
  # Loss function
  loss_fn_path: "./resources/loss/flamby_ixi.py"
  loss_fn_name: "BaselineLoss"
  # Client validation
  do_validation: True
  do_pre_validation: True
  metric_path: "./resources/metric/flamby_ixi.py"
  metric_name: "metric"
  # Differential privacy
  use_dp: False
  # Data loader
  train_batch_size: 2
  val_batch_size: 2
  train_data_shuffle: True
  val_data_shuffle: False
  device: "cuda"
  # Logging and outputs
  logging_output_dirname: "./output"
  logging_output_filename: "result"

model_configs:
  model_path: "./resources/model/unet.py"
  model_name: "Baseline"

# Local dataset
data_configs:
  dataset_path: "./resources/dataset/flamby_dataset.py"
  dataset_name: "get_flamby"
  dataset_kwargs:
    dataset: "IXI"
    num_clients: 3
    client_id: 2
