train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client3"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./resources/dataset/coronahack_dataset.py"
  dataset_name: "get_corona"
  dataset_kwargs:
    num_clients: 4
    client_id: 2

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False