train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client2"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./resources/dataset/flamby_dataset.py"
  dataset_name: "get_flamby"
  dataset_kwargs:
    dataset: "TcgaBrca"
    num_clients: 2
    client_id: 1

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False