type: iceadmm
servername: ICEADMMServer
clientname: ICEADMMClient

args:
  num_local_epochs: 10  

  accum_grad: True
  coeff_grad: True
  
  # Optimizer for a gradient calculation (esp., to use zero.grad)
  optim: SGD
  optim_args:    
    lr: 0.01
    # momentum: 0.9
    # weight_decay: 1e-5

  # ADMM parameters  
  init_penalty: 0
  init_proximity: 0

  # Privacy
  privacy: False
  scale_value: 0
  epsilon: inf
 
  
  