server:
  device: cuda:0
  data_dir  : "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/datasets/server"
  output_dir: "./log_funcx_appfl/server"
  s3_bucket: anl-appfl
  
clients:
  - name: uiuc-cig-01-gpu-02
    endpoint_id: a719450f-4721-4ef1-a5e8-5a22b772d354
    device:  cuda:0 
    data_split: 0
    data_dir  : "/mnt/data0-nfs/shared-datasets/anl-covid-xray/archive/"
    output_dir: "/mnt/data0-nfs/hthieu/anl/APPFL/examples/log_funcx_appfl/uiuc-cig-02-gpu-00"
    get_data:
      script_file: "./datasets/covid19_argonne.py"
      call:   "get_data"
    data_pipeline: 
      resize: 224
      num_pixel: 224
      split_file: "split1"