server:
  device: cuda:0
  data_dir  : "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/datasets/server"
  output_dir: "./log_funcx_appfl/server"
  s3_bucket: anl-appfl
  
clients:
  # @Argonne: ALCF ThetaGPU clusters 
  - name: thetagpu-1
    endpoint_id: bf4897e1-83c6-4f29-9b12-b28c289cf7d8
    device: cuda:0
    data_split: 3
    data_dir  : "/eagle/covid-xray/archive/"
    output_dir: "/eagle/covid-xray/log/theta-client-1"
    get_data:
      script_file: "./datasets/covid19_argonne.py"
      call:   "get_data"
    data_pipeline: 
      resize: 224
  
  # @UChicago: 



  # # LCRC CPU clusters
  # - name: bebop-cpu-1
  #   endpoint_id: c50b2423-6f92-4b62-9eb0-dbb89d824b35
  #   device: cpu
  #   data_split: 4
  #   data_dir  : "./data/bebop-cpu-1"
  #   output_dir: "./log/bebop-cpu-1"

  # - name: bebop-cpu-2
  #   endpoint_id: d6c2a151-b1a1-4a9d-9365-ec84ba1c1583
  #   device: cpu
  #   data_split: 5
  #   data_dir  : "./data/bebop-cpu-2"
  #   output_dir: "./log/bebop-cpu-2"
  
  ## LCRC GPU clusters
  # - name: swing-gpu-1
  #   endpoint_id: a63472c2-51a3-4065-88de-d238cd24542b
  #   device: cuda:0
  #   data_split: 0
  #   data_dir  : "./data/swing-gpu-1"
  #   output_dir: "./log/swing-gpu-1"
  