server:
  device: cuda:0
  data_dir  : "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/datasets/server"
  output_dir: "./log_funcx_appfl/server"
  s3_bucket: anl-appfl
  
clients:
  # @UIUC: Argonne Covid dataset 
  # - name: uiuc-cig-01-gpu-02
  #   endpoint_id: a719450f-4721-4ef1-a5e8-5a22b772d354
  - name: uiuc-cig-01-gpu-02
    endpoint_id: c575f4f8-8162-4497-9891-db3c0ab2bb8f
    device:  cuda:0 
    data_split: 0
    data_dir  : "/mnt/data0-nfs/shared-datasets/anl-covid-xray/archive/"
    output_dir: "/mnt/data0-nfs/hthieu/anl/APPFL/examples/log_funcx_appfl/uiuc-cig-02-gpu-00"
    get_data:
      script_file: "./datasets/covid19_argonne.py"
      call:   "get_data"
    data_pipeline: 
      resize: 256
      center_crop: 224
      split_file: "split2"
      train_mean: [0.485, 0.456, 0.406]
      train_std: [0.229, 0.224, 0.225]
      test_mean: [0.485, 0.456, 0.406]
      test_std: [0.229, 0.224, 0.225]

  - name: uchicago-gpu
    endpoint_id: 83d214ed-c5d5-45a0-aa42-9a6e1766a315
    device: cuda:0
    data_split: 0
    # data_dir  : "/nfs/kitbag/COVID19/MIDRC_Data_04-04-23_Processed_Images/"
    data_dir: "/nfs/kitbag/COVID19/MIDRC_Data_04-04-23_Processed_Images_Corrected/"
    output_dir: "/nfs/kitbag/data1/jdfuhrman/MIDRC/APPFLCollab/Logs"
    get_data:
      script_file: "./datasets/covid19_midrc.py"
      call:   "get_data"
    data_pipeline:
      # test_annotation_dir:  "/nfs/kitbag/data1/jdfuhrman/MIDRC/MIDRC_Files/midrc_full_annotations_04-04-23.csv"
      # test_annotation_dir:  "/nfs/kitbag/data1/jdfuhrman/MIDRC/MIDRC_Files/midrc_full_annotations_04-04-23_filtered.csv"
      train_annotation_dir: "/nfs/kitbag/data1/jdfuhrman/MIDRC/MIDRC_Files/MIDRC_Train.csv"
      test_annotation_dir: "/nfs/kitbag/data1/jdfuhrman/MIDRC/MIDRC_Files/MIDRC_Test.csv"
      num_pixels: 224
      train_mean: [0.485, 0.456, 0.406]
      train_std: [0.229, 0.224, 0.225]
      test_mean: [0.485, 0.456, 0.406]
      test_std: [0.229, 0.224, 0.225]
