server:
  device: cuda:0
  data_dir  : "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/datasets/server"
  output_dir: "./log_funcx_appfl/server"
  s3_bucket: anl-appfl
  
clients:
  - name: uiuc-cig-01-gpu-02
    endpoint_id: a719450f-4721-4ef1-a5e8-5a22b772d354
    device:  cuda:0
    data_split: 0
    output_dir: "/mnt/data0-nfs/hthieu/anl/APPFL/examples/log_funcx_appfl/uiuc-cig-02-gpu-00"
    get_data:
      script_file: "./datasets/ecg_broad.py"
      call:   "get_data"
    data_pipeline:
      meta_path : "/mnt/data0-nfs/hthieu/anl/palisades/data/freeze/BROAD_ml4h_klarqvist___physionet__meta_data__graded_splits__72a414d507ba485db4bc5da0e97ecf2b.pq"
      h5py_path : "/mnt/data0-nfs/hthieu/anl/palisades/data/freeze/BROAD_ml4h_klarqvist___physionet__waveforms__596f28a0e7254e3da30c369769f7312e__combined.h5"
  