server:
  device: cuda:0
  data_dir  : "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/datasets/server"
  output_dir: "./log_funcx_appfl/server"
  s3_bucket: anl-appfl

clients:
  # - name: uiuc-cig-01-gpu-02
  #   endpoint_id: a719450f-4721-4ef1-a5e8-5a22b772d354
  #   device:  cuda:0 
  #   data_split: 0
  #   data_dir  : "/mnt/data0-nfs/shared-datasets/anl-covid-xray/archive/"
  #   output_dir: "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/examples/log_funcx_appfl/uiuc-cig-01-gpu-02"
  #   get_data:
  #     script_file: "./datasets/torchvision_datasets.py"
  #     call: get_data

  - name: uiuc-cig-02-gpu-00
    endpoint_id: 4420b006-c767-4ee3-a72a-d0212a657387
    device:  cuda:0 
    data_split: 0
    data_dir  : "/mnt/data0-nfs/hthieu/anl/APPFL-funcX/datasets/clients-data"
    output_dir: "/mnt/data0-nfs/hthieu/anl/APPFL/examples/log_funcx_appfl/uiuc-cig-02-gpu-00"
    get_data:
      script_file: "./datasets/torchvision_datasets.py"
      call: get_data