client_id: "Client2"
train_configs:
  # Device
  bundle_root: "./resources/monai/job/app/config/spleen_ct_segmentation"
  # Logging and outputs
  logging_output_dirname: "./output"
  logging_output_filename: "result"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 10485760
    use_ssl: False
