client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "epoch"
    num_local_epochs: 1
    optim: "Adam"
    optim_args:
      lr: 5e-4
    scheduler: "MultiStepLR"
    scheduler_args:
      milestones: [3, 5, 7, 9, 11, 13, 15, 17]
      gamma: 0.5
    # Loss function
    loss_fn_path: "./resources/loss/flamby_fed_isic2019.py"
    loss_fn_name: "BaselineLoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/flamby_fed_isic2019.py"
    metric_name: "metric"
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    num_workers: 8
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/model/flamby_fed_isic2019.py"
    model_name: "Baseline"

  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

server_configs:
  num_clients: 6
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 20
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
      trusted: True
