node_id: HFLNode1 # This is for simple debugging and should be unqiue!
scheduler: "SyncScheduler"
scheduler_kwargs:
  num_clients: 2
aggregator: "HFLFedAvgAggregator"
aggregator_kwargs:
  lr: 0.5
device: "cpu"
logging_output_dirname: "./output"
logging_output_filename: "result"
comm_configs:
  grpc_configs:
    connect:
      server_uri: localhost:50053
      max_message_size: 1048576
      use_ssl: False
    serve:
      server_uri: localhost:50052
      max_message_size: 1048576
      use_ssl: False