algorithm:
  servername: 'ServerFedAvg'
  clientname: 'ClientOptim'
  args:
    ## Server update
    server_adapt_param: 0.000 #TODO: what is this param?
    ## Clients optimizer
    optim: "SGD"
    num_local_epochs: 1
    optim_args: 
        lr: 0.001
    server_lr_decay_exp_gamma : 0.1
    epsilon: False
    clip_value: False
    clip_norm: 1
    client_weights: "sample_size"

model:
  num_output: 2
  num_domains: 2

loss_params:
  num_output: 2
  num_domains: 2

training:
  num_epochs: 30
  save_model_filename: "Covid_Resnet"

dataset:
  name: CovidDataset

func:
  get_model:
    script_file: "./models/resnet_dda.py"
    call: "get_model"
  get_loss:
    script_file: "./losses/dda_loss.py"
    call: "get_loss"

train_data_batch_size: 256
test_data_batch_size: 256
decay_epochs: [2,3]