client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn: "CrossEntropyLoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/acc.py"
    metric_name: "accuracy"
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/cnn.py"
    model_name: "CNN"
    model_kwargs:
      num_channel: 1
      num_classes: 10
      num_pixel: 28

  dr_metrics: ["ci", "ss"]

server_configs:
  num_clients: 2
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 10
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
