train_configs:
  # Local trainer
  trainer: "NaiveTrainer"
  mode: "step"
  num_local_steps: 100
  optim: "Adam"
  optim_args:
    lr: 0.001
  # Loss function
  loss_fn_path: "./loss/celoss.py"
  loss_fn_name: "CELoss"
  # Client validation
  do_validation: True
  do_pre_validation: True
  metric_path: "./metric/acc.py"
  metric_name: "accuracy"
  # Differential privacy
  use_dp: False
  # Data loader
  train_batch_size: 64
  val_batch_size: 64
  train_data_shuffle: True
  val_data_shuffle: False
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client0"
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  
model_configs:
  seed: 42
  model_path: "./model/cnn.py"
  model_name: "CNN"
  model_kwargs:
    num_channel: 1
    num_classes: 10
    num_pixel: 28

data_configs:
  dataset_path: "./dataset/mnist_dataset.py"
  dataset_name: "get_mnist"
  dataset_kwargs:
    num_clients: 3
    client_id: 0
    partition_strategy: "class_noniid"
    visualization: True
    output_dirname: "./output"
    output_filename: "visualization.pdf"

num_epochs: 10
aggregator: "DFLNodeFedAvgAggregator"
comm_configs:
  grpc_configs:
    serve:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
    connect:
      - server_uri: localhost:50052
        max_message_size: 1048576
        use_ssl: False
      - server_uri: localhost:50053
        max_message_size: 1048576
        use_ssl: False
