name: Enhancement Request
description: Request a new feature or enhancement.
labels: ["enhancement"]
assignees:
  - Zilinghan
body:
  - type: textarea
    id: request
    attributes:
      label: Describe the Request
      description: >
        Please describe your use case and why the current feature set does
        not satisfy your needs.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Sample Code
      description: >
        If relevant, please provide sample code such as the proposed
        interface, usage, or results. **Note:** this will be rendered as
        Python code automatically.
      render: python
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Code or Information
      description: >
        Optional space for additional code or text. **Note:** this will
        be rendered as console text automatically.
      render: console
    validations:
      required: false
