name: Usage Questions
description: Questions about how to use the package.
labels: ["question"]
assignees:
  - Zilinghan
body:
  - type: textarea
    id: question
    attributes:
      label: Describe the Question
      description: >
        Please describe the question you have about using the package.
    validations:
      required: true
