name: Other Help
description: Other questions or requests for help.
labels: ["help wanted"]
assignees:
  - Zilinghan
body:
  - type: textarea
    id: help
    attributes:
      label: Describe the Request
      description: >
        Please describe the question or request for help.
    validations:
      required: true
