server:
  device: cpu
  data_dir  : "./log_globus_compute_appfl/superglue_fedavg_server"
  output_dir: "./log_globus_compute_appfl/superglue_fedavg_server"
  s3_bucket: "appflx-models"
  s3_creds: "globus_compute/creds/credential.csv"

algorithm:
  servername: 'ServerFedAvg'
  clientname: 'GlobusComputeClientLLMFineTuneOptim'
  args:
    ## Clients optimizer
    optim: "AdamW"
    num_local_epochs: 1
    optim_args: 
      lr: 0.0001
    scheduler_args:
      step_size: 1
      gamma: 0.85    
    client_weights: "equal"
    ## Differential Privacy
    use_dp: False
    clip_grad: False
  
training:
  num_epochs: 1
  train_data_batch_size: 4
  test_data_batch_size: 4
  save_model_dirname: "./model/cb"
  save_model_filename: "lora_globus_compute"
  send_final_model: True
  client_do_validation: True
  client_do_testing: True
  server_do_validation: False
  server_do_testing: False

custom_configs:
  lora_configs:
    r: 8
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj"]
    bias: "none"
    lora_dropout: 0.05
  training_configs:
    model_name: /projects/bbke/zl52/llama2/llama/models_hf/7B_chat
    gradient_accumulation_steps: 1
