client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.1
    # Loss function
    loss_fn_path: "./resources/loss/coxloss.py"
    loss_fn_name: "BaselineLoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/c_index.py"
    metric_name: "metric"
    send_gradient: True
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: True
    clip_value: 0.5
    clip_norm: 1
    # Data loader
    train_batch_size: 8
    val_batch_size: 8
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/model/fc.py"
    model_name: "FC"
    model_kwargs:
      input_size: 39
  
  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

server_configs:
  scheduler: "CompassScheduler"
  scheduler_kwargs:
    num_clients: 4
    same_init_model: True
    max_local_steps: 100
    min_local_steps: 20
    speed_momentum: 0.9
    latest_time_factor: 1.5
  aggregator: "FedCompassAggregator"
  aggregator_kwargs:
    weights: "equal"
    staleness_fn: "polynomial"
    staleness_fn_kwargs:
      a: 0.5
    alpha: 0.9
    gradient_based: True
    num_clients: 4
  device: "cpu"
  num_global_epochs: 50
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False