type: fedavg
servername: FedAvgServer
clientname: FedAvgClient

args:  
  num_local_epochs: 10

  # Optimizer
  optim: SGD
  optim_args:    
    lr: 0.01
    momentum: 0.9
    weight_decay: 1e-5

  # Privacy
  privacy: False
  scale_value: 0
  epsilon: inf
