type: fedavg
servername: FedAvgServer
clientname: FedAvgClient

args:  
  num_local_epochs: 10

  ## Optimizer
  optim: SGD
  optim_args:    
    lr: 0.01
    momentum: 0.9
    weight_decay: 1e-5

  ## Differential Privacy 
  #  epsilon: "inf"'  (non-private)
  #  Stronger privacy as epsilon decreases
  epsilon: 1

  ## Gradient Clipping
  # clip_value: "inf"
  clip_value: 1
  clip_norm: 1


