type: iiadmm
servername: IIADMMServer
clientname: IIADMMClient

args:
  num_local_epochs: 10  
  
  accum_grad: True
  coeff_grad: True

  # Optimizer for a gradient calculation (esp., to use zero.grad)
  optim: SGD
  optim_args:    
    lr: 0
    # momentum: 0.9
    # weight_decay: 1e-5

  # ADMM penalty
  init_penalty: 100.0     

  # Privacy
  privacy: False
  scale_value: 0
  epsilon: inf
 
  
  