client_id: "Client1"
train_configs:
  # Device
  device: "cuda"
  # Logging and outputs
  logging_output_dirname: "./output"
  logging_output_filename: "result_decentralized_fc"

# Local dataset (CIFAR-10, non-IID partition: 2 classes per client)
data_configs:
  dataset_path: "./resources/dataset/cifar10_dimat.py"
  dataset_name: "get_cifar10"
  dataset_kwargs:
    num_clients: 5
    client_id: 0
    num_classes_per_client: 2

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False
