client_id: "Client1"
train_configs:
  device: "cuda"
  logging_output_dirname: "./output"
  logging_output_filename: "result"
data_configs:
  dataset_path: "./resources/dataset/cifar10_dimat_iid.py"
  dataset_name: "get_cifar10"
  dataset_kwargs:
    num_clients: 5
    client_id: 0
    visualization: True
    output_dirname: "./output"
    output_filename: "visualization.pdf"
comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False
