client_configs:
  train_configs:
    trainer: "VanillaTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
    loss_fn_path: "./resources/loss/simple_loss.py"
    loss_fn_name: "SimpleLoss"
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/model/simple_model.py"
    model_name: "TinyNet"
    model_kwargs:
      input_size: 8
      num_classes: 2

  comm_configs:
    compressor_configs:
      enable_compression: False

server_configs:
  num_clients: 2
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 10
  server_validation: False
  logging_output_dirname: "./output"
  logging_output_filename: "tes_s3_result"
  comm_configs:
    tes_configs:
      file_storage: "s3"
      file_storage_kwargs:
        s3_bucket: "appfl-test-demo-bkt"
        s3_region: "us-east-1"
        presigned_url_expiry: 3600  # 1 hour
        # Optional: provide AWS credentials explicitly. Alternatively, you can use aws-cli to specify these information
        # aws_access_key_id: "${AWS_ACCESS_KEY_ID}"  
        # aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"