client_configs:
  train_configs:
    # Local trainer
    trainer: "TimesfmTrainer"
    trainer_path: "./resources/trainer/timesfm_trainer.py"
    mode: "epoch"
    num_local_epochs: 1
    optim: "Adam"
    optim_args:
      lr: 5e-6
      weight_decay: 0.9
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 512
    val_batch_size: 512
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/model/timesfm.py"
    model_name: "get_timesfm"
    model_kwargs:
      state_dict_path: "torch_model.ckpt"

  # comm_configs will be copied to server_configs as well
  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

server_configs:
  num_clients: 2
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 5
  server_validation: False
  logging_output_dirname: "./output"
  logging_output_filename: "timesfm_0.02_fedavg"
  comm_configs:
    proxystore_configs:
      enable_proxystore: True
      connector_type: "EndpointConnector"
      connector_configs:
        endpoints: ["1becb3c3-fdb4-4dfb-a07f-89c363ce0a75", "1becb3c3-fdb4-4dfb-a07f-89c363ce0a75", "c767bedb-56bb-4b61-b004-2d60b4d1a6c3"]
