client_configs:
  train_configs:
    # Local trainer
    trainer: "NaiveTrainer"
    mode: "step"
    num_local_steps: 50
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn_path: "../loss/bceloss.py"
    loss_fn_name: "BaselineLoss"
    # Client validation
    do_validation: False
    do_pre_validation: False
    metric_path: "../metric/binary_acc.py"
    metric_name: "metric"
    # Differential privacy
    use_dp: True
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 4
    val_batch_size: 4
    train_data_shuffle: True
    val_data_shuffle: False
    
  model_configs:
    model_path: "../model/linear.py"
    model_name: "Baseline"
    model_kwargs:
      input_dim: 13
      output_dim: 1

server_configs:
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    num_clients: 2
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 10
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
  val_data_configs:
    dataset_path: "../dataset/flamby_dataset.py"
    dataset_name: "get_flamby"
    dataset_kwargs:
      dataset: "HeartDisease"
      test_only: True
    batch_size: 4
  