train_configs:
  # Device
  device: "cuda"
  # Logging and outputs
  logging_id: "Client1"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "../dataset/flamby_dataset.py"
  dataset_name: "get_flamby"
  dataset_kwargs:
    dataset: "ISIC2019"
    num_clients: 6
    client_id: 0