client_configs:
  train_configs:
    # Local trainer
    trainer: "NaiveTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.0005
    # Loss function
    loss_fn_path: "../loss/focalloss.py"
    loss_fn_name: "BaselineLoss"
    # Client validation
    do_validation: False
    do_pre_validation: False
    metric_path: "../metric/balanced_acc.py"
    metric_name: "metric"
    # Differential privacy
    use_dp: True
    epsilon: 0.1
    clip_grad: True
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False
    
  model_configs:
    model_path: "../model/efficientnet.py"
    model_name: "Baseline"

server_configs:
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    num_clients: 6
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cuda"
  num_global_epochs: 20
  logging_output_dirname: "./output"
  logging_output_filename: "result-ISIC-EP01"
  val_data_configs:
    dataset_path: "../dataset/flamby_dataset.py"
    dataset_name: "get_flamby"
    dataset_kwargs:
      dataset: "ISIC2019"
      test_only: True
    batch_size: 64
  