algorithm:
  servername: 'ServerFedAvg'
  clientname: 'ClientOptim'
  args:
    ## Server update
    server_adapt_param: 0.000 #TODO: what is this param?
    ## Clients optimizer
    optim: "SGD"
    num_local_epochs: 1
    optim_args: 
        lr: 0.001
    server_lr_decay_exp_gamma : 0.1
    epsilon: False
    clip_value: False
    clip_norm: 1
    client_weights: "sample_size"

model:
  num_output: 2

  # cohen+actmed
  num_output: 2
  steps: 40
  lr: 0.001
  update_bn: True
  update_fc: False
  bn_mode: "adaptation" # none, adaptation or fixed
  unsupervised: True

training:
  num_epochs: 4
  save_model_filename: "Covid_Resnet"

dataset:
  name: CovidDataset

func:
  get_model:
    script_file: "./models/resnet_tent_adapt_test.py"
    call: "get_model"

train_data_batch_size: 256
test_data_batch_size: 128
decay_epochs: [2,3]