client_configs:
  train_configs:
    # Local trainer
    trainer: "IIADMMTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Algorithm specific
    accum_grad: True
    coeff_grad: False
    init_penalty: 100.0
    residual_balancing:
      res_on: False
      res_on_every_update: False
      tau: 1.1
      mu: 10
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    pre_validation_interval: 1
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False
    
  model_configs:
    model_path: "./resources/model/cnn.py"
    model_name: "CNN"
    model_kwargs:
      num_channel: 1
      num_classes: 10
      num_pixel: 28
  
  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

  data_readiness_configs:
    generate_dr_report: True
    output_dirname: "./output"
    output_filename: "data_readiness_report"
    dr_metrics: 
      class_imbalance: True
      sample_size: True
      num_classes: True
      data_shape: True
      completeness: True
      data_range: True
      sparsity: True
      variance: True
      skewness: True
      entropy: True
      kurtosis: True
      class_distribution: True
      brisque: True
      sharpness: False
      plot:
        class_distribution_plot: True
        data_sample_plot: True
        data_distribution_plot: True
        class_variance_plot: True

server_configs:
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    num_clients: 2
    same_init_model: True
  aggregator: "IIADMMAggregator"
  aggregator_kwargs:
    num_clients: 2
  device: "cpu"
  num_global_epochs: 10
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False