client_configs:
  train_configs:
    trainer: VanillaTrainer
    mode: step
    num_local_steps: 100
    optim: Adam
    optim_args:
      lr: 0.001
    loss_fn_path: ./resources/loss/celoss.py
    loss_fn_name: CELoss
    do_validation: true
    do_pre_validation: true
    metric_path: ./resources/metric/acc.py
    metric_name: accuracy
    use_dp: false
    epsilon: 1
    clip_grad: false
    clip_value: 1
    clip_norm: 1
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: true
    val_data_shuffle: false
  model_configs:
    model_path: ./resources/model/cnn.py
    model_name: CNN
    model_kwargs:
      num_channel: 1
      num_classes: 2
      num_pixel: 28
  comm_configs:
    compressor_configs:
      enable_compression: false
      lossy_compressor: SZ2Compressor
      lossless_compressor: blosc
      error_bounding_mode: REL
      error_bound: 1e-3
      param_cutoff: 1024
  data_readiness_configs:
    generate_dr_report: true
    output_dirname: ./output
    output_filename: data_readiness_report
    dr_metrics:
      class_imbalance: true
      sample_size: true
      num_classes: false
      data_shape: false
      completeness: false
      data_range: false
      variance: true
      skewness: true
      entropy: true
      kurtosis: true
      class_distribution: false
      brisque: true
      sharpness: true
      total_variation: true
      plot:
        class_distribution_plot: true
        data_sample_plot: true
        data_distribution_plot: false
        class_variance_plot: false
        outlier_detection_plot: false
      combine:
        feature_space_distribution: false
server_configs:
  num_clients: 2
  scheduler: SyncScheduler
  scheduler_kwargs:
    same_init_model: true
  aggregator: FedYogiAggregator
  aggregator_kwargs:
    client_weights_mode: equal
    server_learning_rate: 0.01
    server_adapt_param: 1e-3
    server_momentum_param_1: 0.9
    server_momentum_param_2: 0.99
  device: cpu
  num_global_epochs: 10
  logging_output_dirname: ./output
  logging_output_filename: result
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: false
