# APPFL TES Server Configuration for MNIST
# This configuration enables federated learning using GA4GH Task Execution Service (TES)

server_configs:
  scheduler: "SyncScheduler"
  aggregator: "FedAvgAggregator"
  num_global_epochs: 10
  logging_output_dirname: "./output"
  logging_output_filename: "server"
  
  # TES Communication Configuration
  comm_configs:
    tes_configs:
      # GA4GH TES endpoint URL
      tes_endpoint: "https://your-tes-endpoint.org"
      
      # Authentication token for TES API (optional)
      auth_token: "${TES_AUTH_TOKEN}"
      
      # Docker image containing APPFL client environment
      docker_image: "appfl/client:latest"
      
      # Resource requirements for each client task
      resource_requirements:
        cpu_cores: 2
        ram_gb: 4.0
        disk_gb: 20.0
        preemptible: false

  # Aggregator configuration  
  aggregator_kwargs:
    num_clients: 2

  # Scheduler configuration
  scheduler_kwargs:
    num_clients: 2
    same_init_model: true

client_configs:
  train_configs:
    trainer: "VanillaTrainer"
    mode: "step_by_step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
  
  model_configs:
    model: "CNN"
    model_kwargs: {}
  
  data_configs:
    dataset: "MNIST"
    num_workers: 1
    batch_size: 64
    train_data_kwargs: {}
    val_data_kwargs: {}
  
  # Logging configuration for clients
  logging_id: "mnist_tes_client"