client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False

  data_readiness_configs:
    generate_dr_report: True
    output_dirname: "./output"
    output_filename: "data_readiness_report"
    dr_metrics:
      class_imbalance: False
      sample_size: True
      num_classes: False
      data_shape: False
      completeness: False
      data_range: False
      sparsity: False
      variance: False
      skewness: False
      entropy: False
      kurtosis: False
      class_distribution: False
      brisque: False
      sharpness: False
      total_variation: False
      outlier_propotion: False
      plot:
        class_distribution_plot: true
        data_sample_plot: False
        data_distribution_plot: False
        class_variance_plot: False
      combine:
        feature_space_distribution: False
      dragent_configs:
        dragent_path: ./resources/configs/mnist_dr/dr_agent/handle_ci.py #choose from: handle_noise.py, handle_ci.py, handle_mem.py, handle_outliers.py, handle_duplicates.py
        dragent_name: DRAgentCI
        remedy_action: false  #set true to perform remedy action defined in dragent_path

  model_configs:
    model_path: "./resources/model/cnn.py"
    model_name: "CNN"
    model_kwargs:
      num_channel: 1
      num_classes: 2
      num_pixel: 28

  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

server_configs:
  num_clients: 2
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 10
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 10485760
      use_ssl: False
      trusted: True
