client_id: Client7
train_configs:
  # Device
  device: "cuda:1"
  # Logging and outputs
  logging_id: "Client7"
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  # Simulation
  time_per_step: 0.88906352
  # time_per_step_std: 0.088906352
  time_per_step_std: 0

# Local dataset
data_configs:
  dataset_path: "../dataset/cifar10_dataset.py"
  dataset_name: "get_cifar10"
  dataset_kwargs:
    num_clients: 10
    client_id: 7
    partition_strategy: "class_noniid"
    visualization: False
    output_dirname: "./output"
    output_filename: "visualization.pdf"
    seed: 1

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False