client_configs:
  train_configs:
    # Local trainer
    trainer: "NaiveSimTrainer"
    mode: "step"
    num_local_steps: 200
    optim: "SGD"
    optim_args:
      lr: 0.1
    # Loss function
    loss_fn_path: "../loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    skip_post_validation: True
    metric_path: "../metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 128
    val_batch_size: 128
    train_data_shuffle: True
    val_data_shuffle: False
    
  model_configs:
    model_path: "../model/resnet.py"
    model_name: "ResNet18"
  
  comm_configs:
    compressor_configs:
      enable_compression: False

server_configs:
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    num_clients: 10
    same_init_model: True
  aggregator: "FedAvgMAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
    server_momentum_param_1: 0.9
  device: "cpu"
  num_global_epochs: 20
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False