# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_communicator_new_pb2 as grpc__communicator__new__pb2


class DictionaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDictionary = channel.unary_unary(
                '/dictionary.DictionaryService/SendDictionary',
                request_serializer=grpc__communicator__new__pb2.StringDictionary.SerializeToString,
                response_deserializer=grpc__communicator__new__pb2.Response.FromString,
                )


class DictionaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDictionary(self, request, context):
        """Define an RPC method to send a dictionary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DictionaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDictionary,
                    request_deserializer=grpc__communicator__new__pb2.StringDictionary.FromString,
                    response_serializer=grpc__communicator__new__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictionary.DictionaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DictionaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dictionary.DictionaryService/SendDictionary',
            grpc__communicator__new__pb2.StringDictionary.SerializeToString,
            grpc__communicator__new__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
