# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import grpc_communicator_pb2 as grpc__communicator__pb2


class GRPCCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfiguration = channel.unary_unary(
                '/GRPCCommunicator/GetConfiguration',
                request_serializer=grpc__communicator__pb2.ConfigurationRequest.SerializeToString,
                response_deserializer=grpc__communicator__pb2.ConfigurationResponse.FromString,
                )
        self.GetGlobalModel = channel.unary_stream(
                '/GRPCCommunicator/GetGlobalModel',
                request_serializer=grpc__communicator__pb2.GetGlobalModelRequest.SerializeToString,
                response_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                )
        self.UpdateGlobalModel = channel.stream_stream(
                '/GRPCCommunicator/UpdateGlobalModel',
                request_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
                response_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                )
        self.InvokeCustomAction = channel.unary_unary(
                '/GRPCCommunicator/InvokeCustomAction',
                request_serializer=grpc__communicator__pb2.CustomActionRequest.SerializeToString,
                response_deserializer=grpc__communicator__pb2.CustomActionResponse.FromString,
                )


class GRPCCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGlobalModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeCustomAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfiguration,
                    request_deserializer=grpc__communicator__pb2.ConfigurationRequest.FromString,
                    response_serializer=grpc__communicator__pb2.ConfigurationResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_stream_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=grpc__communicator__pb2.GetGlobalModelRequest.FromString,
                    response_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
            ),
            'UpdateGlobalModel': grpc.stream_stream_rpc_method_handler(
                    servicer.UpdateGlobalModel,
                    request_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                    response_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
            ),
            'InvokeCustomAction': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeCustomAction,
                    request_deserializer=grpc__communicator__pb2.CustomActionRequest.FromString,
                    response_serializer=grpc__communicator__pb2.CustomActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCCommunicator/GetConfiguration',
            grpc__communicator__pb2.ConfigurationRequest.SerializeToString,
            grpc__communicator__pb2.ConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GRPCCommunicator/GetGlobalModel',
            grpc__communicator__pb2.GetGlobalModelRequest.SerializeToString,
            grpc__communicator__pb2.DataBuffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGlobalModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/GRPCCommunicator/UpdateGlobalModel',
            grpc__communicator__pb2.DataBuffer.SerializeToString,
            grpc__communicator__pb2.DataBuffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvokeCustomAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCCommunicator/InvokeCustomAction',
            grpc__communicator__pb2.CustomActionRequest.SerializeToString,
            grpc__communicator__pb2.CustomActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
