# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_communicator_new.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgrpc_communicator_new.proto\x12\ndictionary\"~\n\x10StringDictionary\x12:\n\x07\x65ntries\x18\x01 \x03(\x0b\x32).dictionary.StringDictionary.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2Y\n\x11\x44ictionaryService\x12\x44\n\x0eSendDictionary\x12\x1c.dictionary.StringDictionary\x1a\x14.dictionary.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_communicator_new_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGDICTIONARY_ENTRIESENTRY._options = None
  _STRINGDICTIONARY_ENTRIESENTRY._serialized_options = b'8\001'
  _STRINGDICTIONARY._serialized_start=43
  _STRINGDICTIONARY._serialized_end=169
  _STRINGDICTIONARY_ENTRIESENTRY._serialized_start=123
  _STRINGDICTIONARY_ENTRIESENTRY._serialized_end=169
  _RESPONSE._serialized_start=171
  _RESPONSE._serialized_end=198
  _DICTIONARYSERVICE._serialized_start=200
  _DICTIONARYSERVICE._serialized_end=289
# @@protoc_insertion_point(module_scope)
