
defaults:
  - _self_
  - dataset: mnist   ## mnist, cifar10, covid  
  - model: cnn1      ## cnn1, cnn2  
  - fed: iadmm      ## fedavg, iadmm
  - optim: sgd

device: 'cuda'      ## cuda, cpu
validation: True

num_epochs: 2
batch_size: 64
num_clients: 4

