# A main configuration file

# Each field has its own configuration file.
defaults:
  - _self_  
  - fed: fedavg  

# Number of training epochs
num_epochs: 2

# Training Data Batch Info
batch_training: False
train_data_batch_size: 64
train_data_shuffle: False

# Testing Data Batch Info
test_data_batch_size: 64
test_data_shuffle: False

# Results directory
result_dir: "../../../results" 

# Compute device
device: 'cpu'

# Indication of whether to validate or not
validation: True

#
# gRPC configutations
#

operator:
  id: 1

server:
  id: 1
  host: localhost
  port: 50051

client:
  id: 1
