defaults:
  - _self_
  # - dataset: mnist
  # - dataset: cifar10
  - dataset: covid
  - model: cnn1
  - fed: iadmm
  - optim: sgd

num_epochs: 1000
batch_size: 15000
device: 'cpu'

num_clients: 4
validation: True
