defaults:
  - _self_
  - dataset: mnist
  - model: cnn
  - fed: fedavg
  - optim: sgd

num_epochs: 2
batch_size: 64
device: 'cpu'

num_clients: 1
validation: True

operator:
  id: 1

server:
  id: 1
  host: localhost
  port: 50051

client:
  id: 1
