
defaults:
  - _self_
  # - dataset: mnist
  # - dataset: cifar10
  - dataset: covid
  - model: cnn1
  - fed: fedavg
  - optim: sgd

  
num_epochs: 10
batch_size: 64
device: 'cpu'

num_clients: 4
validation: True
