
defaults:
  - _self_
  - dataset: mnist  ## mnist, cifar10, covid  
  - model: cnn1      ## cnn1, cnn2  
  - fed: iadmm     ## fedavg, iadmm
  - optim: sgd
  
num_epochs: 10
batch_size: 64
device: 'cpu'

num_clients: 4
validation: True
