defaults:
  - _self_
  - dataset: mnist  ## mnist, cifar10, coronahack, femnist
  - model: cnn1     ## cnn1, cnn2
  - fed: fedavg     ## fedavg, iadmm
  - optim: sgd

num_epochs: 1
batch_size: 64
device: 'cpu'       ## cuda, cpu

num_clients: 1
validation: True

operator:
  id: 1

server:
  id: 1
  host: localhost
  port: 50051

client:
  id: 1
