# A main configuration file

# Each field has its own configuration file.
defaults:
  - _self_  
  - fed: iadmm
  - optim: sgd

# Number of training epochs
num_epochs: 2

# Size of each training batch
batch_size: 16

# Compute device
device: 'cpu'

# Indication of whether to validate or not
validation: True

#
# gRPC configutations
#

operator:
  id: 1

server:
  id: 1
  host: localhost
  port: 50051

client:
  id: 1
