client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/f1score.py"
    metric_name: "f1score"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False
    
  model_configs:
    model_path: "./resources/model/cnn.py"
    model_name: "CNN"
    model_kwargs:
      num_channel: 1
      num_classes: 10
      num_pixel: 28
  
  # comm_configs will be copied to server_configs as well
  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024
    # globus_compute_configs:
    #   s3_bucket: "appflx-models"
    #   s3_creds_file: "./resources/config_gc/creds/credential.csv"
  
  data_readiness_configs:
    generate_dr_report: True
    output_dirname: "./output"
    output_filename: "data_readiness_report"
    dr_metrics: 
      class_imbalance: True
      sample_size: False
      num_classes: False
      data_shape: False
      completeness: True
      data_range: False
      sparsity: False
      variance: False
      skewness: False
      entropy: False
      kurtosis: False
      class_distribution: True
      brisque: False
      sharpness: False
      plot:
        class_distribution_plot: False
        data_sample_plot: False
        data_distribution_plot: False
        class_variance_plot: False
      combine:
        feature_space_distribution: False

server_configs:
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    num_clients: 3
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 2
  server_validation: False
  logging_output_dirname: "./output"
  logging_output_filename: "result"
