train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client1"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./resources/dataset/mnist_dataset.py"
  dataset_name: "get_mnist"
  dataset_kwargs:
    num_clients: 2
    client_id: 0
    partition_strategy: "class_noniid"
    visualization: True
    output_dirname: "./output"
    output_filename: "visualization.pdf"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False

dr_metrics: 
  class_imbalance: True
  sample_size: True
  num_classes: True
  data_shape: True
  completeness: True
  data_range: True
  sparsity: True
  variance: True
  skewness: True
  entropy: True
  kurtosis: True
  class_distribution: True
  brisque: True
  sharpness: False
  total_variation: True
  dataset_name: True
  plot:
    class_distribution_plot: True
    data_sample_plot: True
    data_distribution_plot: True
    class_variance_plot: True