client_id: Client3 # This is for simple debugging and should be unqiue!

train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client3"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./dataset/mnist_dataset.py"
  dataset_name: "get_mnist"
  dataset_kwargs:
    num_clients: 7
    client_id: 3
    partition_strategy: "class_noniid"
    visualization: False
    output_dirname: "./output"
    output_filename: "visualization.pdf"

comm_configs:
  grpc_configs:
    connect:
      - server_uri: localhost:50052
        max_message_size: 1048576
        use_ssl: False
