train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client1"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
    dataset_path: "./dataset/dummy_dataset.py"
    dataset_name: "get_dummy"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 536870912
    use_ssl: False