# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import grpc_communicator_pb2 as grpc__communicator__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_communicator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GRPCCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfiguration = channel.unary_unary(
                '/GRPCCommunicator/GetConfiguration',
                request_serializer=grpc__communicator__pb2.ConfigurationRequest.SerializeToString,
                response_deserializer=grpc__communicator__pb2.ConfigurationResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_stream(
                '/GRPCCommunicator/GetGlobalModel',
                request_serializer=grpc__communicator__pb2.GetGlobalModelRequest.SerializeToString,
                response_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                _registered_method=True)
        self.UpdateGlobalModel = channel.stream_stream(
                '/GRPCCommunicator/UpdateGlobalModel',
                request_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
                response_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                _registered_method=True)
        self.InvokeCustomAction = channel.stream_stream(
                '/GRPCCommunicator/InvokeCustomAction',
                request_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
                response_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                _registered_method=True)


class GRPCCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGlobalModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeCustomAction(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfiguration,
                    request_deserializer=grpc__communicator__pb2.ConfigurationRequest.FromString,
                    response_serializer=grpc__communicator__pb2.ConfigurationResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_stream_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=grpc__communicator__pb2.GetGlobalModelRequest.FromString,
                    response_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
            ),
            'UpdateGlobalModel': grpc.stream_stream_rpc_method_handler(
                    servicer.UpdateGlobalModel,
                    request_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                    response_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
            ),
            'InvokeCustomAction': grpc.stream_stream_rpc_method_handler(
                    servicer.InvokeCustomAction,
                    request_deserializer=grpc__communicator__pb2.DataBuffer.FromString,
                    response_serializer=grpc__communicator__pb2.DataBuffer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GRPCCommunicator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GRPCCommunicator/GetConfiguration',
            grpc__communicator__pb2.ConfigurationRequest.SerializeToString,
            grpc__communicator__pb2.ConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/GRPCCommunicator/GetGlobalModel',
            grpc__communicator__pb2.GetGlobalModelRequest.SerializeToString,
            grpc__communicator__pb2.DataBuffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGlobalModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/GRPCCommunicator/UpdateGlobalModel',
            grpc__communicator__pb2.DataBuffer.SerializeToString,
            grpc__communicator__pb2.DataBuffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeCustomAction(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/GRPCCommunicator/InvokeCustomAction',
            grpc__communicator__pb2.DataBuffer.SerializeToString,
            grpc__communicator__pb2.DataBuffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
