name: build-polaris-test

on:
  push:
    branches: [ zilinghan/cicd-polaris ]
    paths-ignore:
      - 'docs/**'

jobs:
  polaris:
    runs-on: ubuntu-22.04
    steps:
    - name: Trigger gitlab-ci
      run: |
        curl -X POST --fail \
          -F token=${{ secrets.ALCF_GITLAB_CI_TOKEN }} -F ref=main \
          -F variables[TRIGGER_GITHUB_SHA]=${{ github.sha }} \ 
          https://gitlab-ci.alcf.anl.gov/api/v4/projects/171/trigger/pipeline