type: fedavg
servername: FedAvgServer
clientname: FedAvgClient

args:  
  num_local_epochs: 10
  
  # Privacy
  privacy: False
  scale_value: 0
  epsilon: inf

  # Gradient Clipping
  clip_value: inf
  clip_norm: 1
  