type: iadmm
servername: IADMMServer
clientname: IADMMClient

args:
  num_local_epochs: 10  
  
  # ADMM penalty
  penalty: 100.0     

  # Privacy
  privacy: False
  scale_value: 0.01
  epsilon: inf

  # Gradient Clipping
  clip_value: inf
  clip_norm: 1
  
  