client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "epoch"
    num_local_epochs: 1
    optim: "Adam"
    optim_args:
      lr: 0.0001
      weight_decay: 0.0001
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False
    num_workers: 4

  model_configs:
    model_path: "./resources/model/resnet_aireadi.py"
    model_name: "ResNet50"
    model_kwargs:
      num_classes: 4


server_configs:
  num_clients: 2
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 3
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: 0.0.0.0:50051
      max_message_size: 1048576
      use_ssl: False
